DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;

DROP TYPE IF EXISTS room_type CASCADE;

DROP TYPE IF EXISTS job_type CASCADE;

DROP TYPE IF EXISTS sleep_wake_schedule CASCADE;

DROP TYPE IF EXISTS cleaning_schedule CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS user_preferences CASCADE;

DROP TABLE IF EXISTS user_roommate_preferences CASCADE;

DROP TABLE IF EXISTS user_photos CASCADE;

DROP TABLE IF EXISTS user_tracks CASCADE;

DROP TABLE IF EXISTS neighborhoods CASCADE;

